/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex{}

// GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex The line boundary crossing direction vertex
type GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex struct {
	// The vertex x coordinate
	X *float32 `json:"x,omitempty"`
	// The vertex y coordinate
	Y *float32 `json:"y,omitempty"`
}

// NewGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex instantiates a new GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex() *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex {
	this := GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex{}
	return &this
}

// NewGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertexWithDefaults instantiates a new GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertexWithDefaults() *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex {
	this := GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex{}
	return &this
}

// GetX returns the X field value if set, zero value otherwise.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) GetX() float32 {
	if o == nil || IsNil(o.X) {
		var ret float32
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) GetXOk() (*float32, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given float32 and assigns it to the X field.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) SetX(v float32) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) GetY() float32 {
	if o == nil || IsNil(o.Y) {
		var ret float32
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) GetYOk() (*float32, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given float32 and assigns it to the Y field.
func (o *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) SetY(v float32) {
	o.Y = &v
}

func (o GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	return toSerialize, nil
}

type NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex struct {
	value *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex
	isSet bool
}

func (v NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) Get() *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex {
	return v.value
}

func (v *NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) Set(val *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex(val *GetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) *NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex {
	return &NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex{value: val, isSet: true}
}

func (v NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationCameraBoundariesLinesByDevice200ResponseInnerBoundariesDirectionVertex) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


