/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 05 July, 2023 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.35.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp{}

// GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp Lldp information
type GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp struct {
	// Port Id
	PortId *string `json:"portId,omitempty"`
}

// NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp instantiates a new GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp {
	this := GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp{}
	return &this
}

// NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldpWithDefaults instantiates a new GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldpWithDefaults() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp {
	this := GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp{}
	return &this
}

// GetPortId returns the PortId field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) GetPortId() string {
	if o == nil || IsNil(o.PortId) {
		var ret string
		return ret
	}
	return *o.PortId
}

// GetPortIdOk returns a tuple with the PortId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) GetPortIdOk() (*string, bool) {
	if o == nil || IsNil(o.PortId) {
		return nil, false
	}
	return o.PortId, true
}

// HasPortId returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) HasPortId() bool {
	if o != nil && !IsNil(o.PortId) {
		return true
	}

	return false
}

// SetPortId gets a reference to the given string and assigns it to the PortId field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) SetPortId(v string) {
	o.PortId = &v
}

func (o GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PortId) {
		toSerialize["portId"] = o.PortId
	}
	return toSerialize, nil
}

type NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp struct {
	value *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp
	isSet bool
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) Get() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp {
	return v.value
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) Set(val *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp(val *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp {
	return &NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp{value: val, isSet: true}
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


