/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower{}

// GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower Apparent power threshold. 'draw' must be provided.
type GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower struct {
	// Alerting threshold in volt-amps. Must be between 0 and 3750.
	Draw float32 `json:"draw"`
}

// NewGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower instantiates a new GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower(draw float32) *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower {
	this := GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower{}
	this.Draw = draw
	return &this
}

// NewGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPowerWithDefaults instantiates a new GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPowerWithDefaults() *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower {
	this := GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower{}
	return &this
}

// GetDraw returns the Draw field value
func (o *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) GetDraw() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Draw
}

// GetDrawOk returns a tuple with the Draw field value
// and a boolean to check if the value has been set.
func (o *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) GetDrawOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Draw, true
}

// SetDraw sets field value
func (o *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) SetDraw(v float32) {
	o.Draw = v
}

func (o GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["draw"] = o.Draw
	return toSerialize, nil
}

type NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower struct {
	value *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower
	isSet bool
}

func (v NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) Get() *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower {
	return v.value
}

func (v *NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) Set(val *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower(val *GetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) *NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower {
	return &NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower{value: val, isSet: true}
}

func (v NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkSensorAlertsProfiles200ResponseInnerConditionsInnerThresholdApparentPower) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


