/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 02 November, 2022 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.27.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// GetOrganizationSensorReadingsHistory200ResponseInnerPm25 Reading for the 'pm25' metric. This will only be present if the 'metric' property equals 'pm25'.
type GetOrganizationSensorReadingsHistory200ResponseInnerPm25 struct {
	// PM2.5 reading in micrograms per cubic meter.
	Concentration *int32 `json:"concentration,omitempty"`
}

// NewGetOrganizationSensorReadingsHistory200ResponseInnerPm25 instantiates a new GetOrganizationSensorReadingsHistory200ResponseInnerPm25 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationSensorReadingsHistory200ResponseInnerPm25() *GetOrganizationSensorReadingsHistory200ResponseInnerPm25 {
	this := GetOrganizationSensorReadingsHistory200ResponseInnerPm25{}
	return &this
}

// NewGetOrganizationSensorReadingsHistory200ResponseInnerPm25WithDefaults instantiates a new GetOrganizationSensorReadingsHistory200ResponseInnerPm25 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationSensorReadingsHistory200ResponseInnerPm25WithDefaults() *GetOrganizationSensorReadingsHistory200ResponseInnerPm25 {
	this := GetOrganizationSensorReadingsHistory200ResponseInnerPm25{}
	return &this
}

// GetConcentration returns the Concentration field value if set, zero value otherwise.
func (o *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) GetConcentration() int32 {
	if o == nil || isNil(o.Concentration) {
		var ret int32
		return ret
	}
	return *o.Concentration
}

// GetConcentrationOk returns a tuple with the Concentration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) GetConcentrationOk() (*int32, bool) {
	if o == nil || isNil(o.Concentration) {
    return nil, false
	}
	return o.Concentration, true
}

// HasConcentration returns a boolean if a field has been set.
func (o *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) HasConcentration() bool {
	if o != nil && !isNil(o.Concentration) {
		return true
	}

	return false
}

// SetConcentration gets a reference to the given int32 and assigns it to the Concentration field.
func (o *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) SetConcentration(v int32) {
	o.Concentration = &v
}

func (o GetOrganizationSensorReadingsHistory200ResponseInnerPm25) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Concentration) {
		toSerialize["concentration"] = o.Concentration
	}
	return json.Marshal(toSerialize)
}

type NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25 struct {
	value *GetOrganizationSensorReadingsHistory200ResponseInnerPm25
	isSet bool
}

func (v NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) Get() *GetOrganizationSensorReadingsHistory200ResponseInnerPm25 {
	return v.value
}

func (v *NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) Set(val *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25(val *GetOrganizationSensorReadingsHistory200ResponseInnerPm25) *NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25 {
	return &NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25{value: val, isSet: true}
}

func (v NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationSensorReadingsHistory200ResponseInnerPm25) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


