/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 03 January, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.42.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner{}

// GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner struct for GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner
type GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner struct {
	// URL to the device
	Url *string `json:"url,omitempty"`
	// Name of the device
	Name *string `json:"name,omitempty"`
	// Product type of the device
	ProductType *string `json:"productType,omitempty"`
	// Serial number of the device
	Serial *string `json:"serial,omitempty"`
	// The mac address of the device
	Mac *string `json:"mac,omitempty"`
	Lldp *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp `json:"lldp,omitempty"`
	// Clients related to the device
	Clients []GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner `json:"clients,omitempty"`
}

// NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner instantiates a new GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner {
	this := GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner{}
	return &this
}

// NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerWithDefaults instantiates a new GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerWithDefaults() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner {
	this := GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetUrl(v string) {
	o.Url = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetName(v string) {
	o.Name = &v
}

// GetProductType returns the ProductType field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetProductType() string {
	if o == nil || IsNil(o.ProductType) {
		var ret string
		return ret
	}
	return *o.ProductType
}

// GetProductTypeOk returns a tuple with the ProductType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetProductTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ProductType) {
		return nil, false
	}
	return o.ProductType, true
}

// HasProductType returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasProductType() bool {
	if o != nil && !IsNil(o.ProductType) {
		return true
	}

	return false
}

// SetProductType gets a reference to the given string and assigns it to the ProductType field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetProductType(v string) {
	o.ProductType = &v
}

// GetSerial returns the Serial field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetSerial() string {
	if o == nil || IsNil(o.Serial) {
		var ret string
		return ret
	}
	return *o.Serial
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetSerialOk() (*string, bool) {
	if o == nil || IsNil(o.Serial) {
		return nil, false
	}
	return o.Serial, true
}

// HasSerial returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasSerial() bool {
	if o != nil && !IsNil(o.Serial) {
		return true
	}

	return false
}

// SetSerial gets a reference to the given string and assigns it to the Serial field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetSerial(v string) {
	o.Serial = &v
}

// GetMac returns the Mac field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetMac() string {
	if o == nil || IsNil(o.Mac) {
		var ret string
		return ret
	}
	return *o.Mac
}

// GetMacOk returns a tuple with the Mac field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetMacOk() (*string, bool) {
	if o == nil || IsNil(o.Mac) {
		return nil, false
	}
	return o.Mac, true
}

// HasMac returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasMac() bool {
	if o != nil && !IsNil(o.Mac) {
		return true
	}

	return false
}

// SetMac gets a reference to the given string and assigns it to the Mac field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetMac(v string) {
	o.Mac = &v
}

// GetLldp returns the Lldp field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetLldp() GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp {
	if o == nil || IsNil(o.Lldp) {
		var ret GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp
		return ret
	}
	return *o.Lldp
}

// GetLldpOk returns a tuple with the Lldp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetLldpOk() (*GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp, bool) {
	if o == nil || IsNil(o.Lldp) {
		return nil, false
	}
	return o.Lldp, true
}

// HasLldp returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasLldp() bool {
	if o != nil && !IsNil(o.Lldp) {
		return true
	}

	return false
}

// SetLldp gets a reference to the given GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp and assigns it to the Lldp field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetLldp(v GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerLldp) {
	o.Lldp = &v
}

// GetClients returns the Clients field value if set, zero value otherwise.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetClients() []GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner {
	if o == nil || IsNil(o.Clients) {
		var ret []GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner
		return ret
	}
	return o.Clients
}

// GetClientsOk returns a tuple with the Clients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) GetClientsOk() ([]GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner, bool) {
	if o == nil || IsNil(o.Clients) {
		return nil, false
	}
	return o.Clients, true
}

// HasClients returns a boolean if a field has been set.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) HasClients() bool {
	if o != nil && !IsNil(o.Clients) {
		return true
	}

	return false
}

// SetClients gets a reference to the given []GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner and assigns it to the Clients field.
func (o *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) SetClients(v []GetNetworkHealthAlerts200ResponseInnerScopeDevicesInnerClientsInner) {
	o.Clients = v
}

func (o GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ProductType) {
		toSerialize["productType"] = o.ProductType
	}
	if !IsNil(o.Serial) {
		toSerialize["serial"] = o.Serial
	}
	if !IsNil(o.Mac) {
		toSerialize["mac"] = o.Mac
	}
	if !IsNil(o.Lldp) {
		toSerialize["lldp"] = o.Lldp
	}
	if !IsNil(o.Clients) {
		toSerialize["clients"] = o.Clients
	}
	return toSerialize, nil
}

type NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner struct {
	value *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner
	isSet bool
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) Get() *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner {
	return v.value
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) Set(val *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner(val *GetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner {
	return &NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner{value: val, isSet: true}
}

func (v NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkHealthAlerts200ResponseInnerScopeDevicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


