/*
Meraki Dashboard API

The Cisco Meraki Dashboard API is a modern REST API based on the OpenAPI specification.  > Date: 07 June, 2023 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.34.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// InlineObject29 struct for InlineObject29
type InlineObject29 struct {
	// The list of connectivity monitoring destinations
	Destinations []NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations `json:"destinations,omitempty"`
}

// NewInlineObject29 instantiates a new InlineObject29 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject29() *InlineObject29 {
	this := InlineObject29{}
	return &this
}

// NewInlineObject29WithDefaults instantiates a new InlineObject29 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject29WithDefaults() *InlineObject29 {
	this := InlineObject29{}
	return &this
}

// GetDestinations returns the Destinations field value if set, zero value otherwise.
func (o *InlineObject29) GetDestinations() []NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations {
	if o == nil || isNil(o.Destinations) {
		var ret []NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations
		return ret
	}
	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject29) GetDestinationsOk() ([]NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations, bool) {
	if o == nil || isNil(o.Destinations) {
    return nil, false
	}
	return o.Destinations, true
}

// HasDestinations returns a boolean if a field has been set.
func (o *InlineObject29) HasDestinations() bool {
	if o != nil && !isNil(o.Destinations) {
		return true
	}

	return false
}

// SetDestinations gets a reference to the given []NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations and assigns it to the Destinations field.
func (o *InlineObject29) SetDestinations(v []NetworksNetworkIdApplianceConnectivityMonitoringDestinationsDestinations) {
	o.Destinations = v
}

func (o InlineObject29) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Destinations) {
		toSerialize["destinations"] = o.Destinations
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject29 struct {
	value *InlineObject29
	isSet bool
}

func (v NullableInlineObject29) Get() *InlineObject29 {
	return v.value
}

func (v *NullableInlineObject29) Set(val *InlineObject29) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject29) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject29) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject29(val *InlineObject29) *NullableInlineObject29 {
	return &NullableInlineObject29{value: val, isSet: true}
}

func (v NullableInlineObject29) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject29) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


