/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the AssignNetworkWirelessEthernetPortsProfiles201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssignNetworkWirelessEthernetPortsProfiles201Response{}

// AssignNetworkWirelessEthernetPortsProfiles201Response struct for AssignNetworkWirelessEthernetPortsProfiles201Response
type AssignNetworkWirelessEthernetPortsProfiles201Response struct {
	// List of updated AP serials
	Serials []string `json:"serials,omitempty"`
	// AP profile ID
	ProfileId *string `json:"profileId,omitempty"`
}

// NewAssignNetworkWirelessEthernetPortsProfiles201Response instantiates a new AssignNetworkWirelessEthernetPortsProfiles201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignNetworkWirelessEthernetPortsProfiles201Response() *AssignNetworkWirelessEthernetPortsProfiles201Response {
	this := AssignNetworkWirelessEthernetPortsProfiles201Response{}
	return &this
}

// NewAssignNetworkWirelessEthernetPortsProfiles201ResponseWithDefaults instantiates a new AssignNetworkWirelessEthernetPortsProfiles201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignNetworkWirelessEthernetPortsProfiles201ResponseWithDefaults() *AssignNetworkWirelessEthernetPortsProfiles201Response {
	this := AssignNetworkWirelessEthernetPortsProfiles201Response{}
	return &this
}

// GetSerials returns the Serials field value if set, zero value otherwise.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) GetSerials() []string {
	if o == nil || IsNil(o.Serials) {
		var ret []string
		return ret
	}
	return o.Serials
}

// GetSerialsOk returns a tuple with the Serials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) GetSerialsOk() ([]string, bool) {
	if o == nil || IsNil(o.Serials) {
		return nil, false
	}
	return o.Serials, true
}

// HasSerials returns a boolean if a field has been set.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) HasSerials() bool {
	if o != nil && !IsNil(o.Serials) {
		return true
	}

	return false
}

// SetSerials gets a reference to the given []string and assigns it to the Serials field.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) SetSerials(v []string) {
	o.Serials = v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) GetProfileId() string {
	if o == nil || IsNil(o.ProfileId) {
		var ret string
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) GetProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given string and assigns it to the ProfileId field.
func (o *AssignNetworkWirelessEthernetPortsProfiles201Response) SetProfileId(v string) {
	o.ProfileId = &v
}

func (o AssignNetworkWirelessEthernetPortsProfiles201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssignNetworkWirelessEthernetPortsProfiles201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Serials) {
		toSerialize["serials"] = o.Serials
	}
	if !IsNil(o.ProfileId) {
		toSerialize["profileId"] = o.ProfileId
	}
	return toSerialize, nil
}

type NullableAssignNetworkWirelessEthernetPortsProfiles201Response struct {
	value *AssignNetworkWirelessEthernetPortsProfiles201Response
	isSet bool
}

func (v NullableAssignNetworkWirelessEthernetPortsProfiles201Response) Get() *AssignNetworkWirelessEthernetPortsProfiles201Response {
	return v.value
}

func (v *NullableAssignNetworkWirelessEthernetPortsProfiles201Response) Set(val *AssignNetworkWirelessEthernetPortsProfiles201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignNetworkWirelessEthernetPortsProfiles201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignNetworkWirelessEthernetPortsProfiles201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignNetworkWirelessEthernetPortsProfiles201Response(val *AssignNetworkWirelessEthernetPortsProfiles201Response) *NullableAssignNetworkWirelessEthernetPortsProfiles201Response {
	return &NullableAssignNetworkWirelessEthernetPortsProfiles201Response{value: val, isSet: true}
}

func (v NullableAssignNetworkWirelessEthernetPortsProfiles201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignNetworkWirelessEthernetPortsProfiles201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


