/*
Meraki Dashboard API

A RESTful API to programmatically manage and monitor Cisco Meraki networks at scale.  > Date: 07 February, 2024 > > [Recent Updates](https://meraki.io/whats-new/)  ---  [API Documentation](https://meraki.io/api)  [Community Support](https://meraki.io/community)  [Meraki Homepage](https://www.meraki.com) 

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner{}

// GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner struct for GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner
type GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner struct {
	// The boundary id
	BoundaryId *string `json:"boundaryId,omitempty"`
	// The boundary type
	Type *string `json:"type,omitempty"`
	Results *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults `json:"results,omitempty"`
}

// NewGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner instantiates a new GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner() *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner {
	this := GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner{}
	return &this
}

// NewGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerWithDefaults instantiates a new GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerWithDefaults() *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner {
	this := GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner{}
	return &this
}

// GetBoundaryId returns the BoundaryId field value if set, zero value otherwise.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetBoundaryId() string {
	if o == nil || IsNil(o.BoundaryId) {
		var ret string
		return ret
	}
	return *o.BoundaryId
}

// GetBoundaryIdOk returns a tuple with the BoundaryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetBoundaryIdOk() (*string, bool) {
	if o == nil || IsNil(o.BoundaryId) {
		return nil, false
	}
	return o.BoundaryId, true
}

// HasBoundaryId returns a boolean if a field has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) HasBoundaryId() bool {
	if o != nil && !IsNil(o.BoundaryId) {
		return true
	}

	return false
}

// SetBoundaryId gets a reference to the given string and assigns it to the BoundaryId field.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) SetBoundaryId(v string) {
	o.BoundaryId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) SetType(v string) {
	o.Type = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetResults() GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults {
	if o == nil || IsNil(o.Results) {
		var ret GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) GetResultsOk() (*GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults and assigns it to the Results field.
func (o *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) SetResults(v GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInnerResults) {
	o.Results = &v
}

func (o GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BoundaryId) {
		toSerialize["boundaryId"] = o.BoundaryId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner struct {
	value *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner
	isSet bool
}

func (v NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) Get() *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner {
	return v.value
}

func (v *NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) Set(val *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner(val *GetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) *NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner {
	return &NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner{value: val, isSet: true}
}

func (v NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationCameraDetectionsHistoryByBoundaryByInterval200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


