/*
Meraki Dashboard API

Testing IdpsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package client

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_client_IdpsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IdpsApiService CreateOrganizationSamlIdp", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var organizationId string

        resp, httpRes, err := apiClient.IdpsApi.CreateOrganizationSamlIdp(context.Background(), organizationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IdpsApiService DeleteOrganizationSamlIdp", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var organizationId string
        var idpId string

        resp, httpRes, err := apiClient.IdpsApi.DeleteOrganizationSamlIdp(context.Background(), organizationId, idpId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IdpsApiService GetOrganizationSamlIdp", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var organizationId string
        var idpId string

        resp, httpRes, err := apiClient.IdpsApi.GetOrganizationSamlIdp(context.Background(), organizationId, idpId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IdpsApiService GetOrganizationSamlIdps", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var organizationId string

        resp, httpRes, err := apiClient.IdpsApi.GetOrganizationSamlIdps(context.Background(), organizationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IdpsApiService UpdateOrganizationSamlIdp", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var organizationId string
        var idpId string

        resp, httpRes, err := apiClient.IdpsApi.UpdateOrganizationSamlIdp(context.Background(), organizationId, idpId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
